-- ============================================================
-- SocialCraft AI — Supabase Schema
-- Run this in the Supabase SQL Editor (Dashboard → SQL Editor)
-- ============================================================

-- Enable pgvector extension for Phase 2 caption embeddings
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================
-- user_profiles
-- Extends Supabase auth.users with app-level preferences
-- ============================================================
CREATE TABLE IF NOT EXISTS user_profiles (
  id                  UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  display_name        TEXT,
  preferred_language  TEXT DEFAULT 'english',
  preferred_tone      TEXT DEFAULT 'casual',
  preferred_platforms TEXT[] DEFAULT '{}',
  emoji_usage         TEXT DEFAULT 'medium',   -- low | medium | high
  avg_caption_length  INT  DEFAULT 100,
  hashtag_count       INT  DEFAULT 6,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_user_profiles_updated_at
  BEFORE UPDATE ON user_profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- captions
-- Every caption generated by the system
-- ============================================================
CREATE TABLE IF NOT EXISTS captions (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        UUID REFERENCES auth.users ON DELETE CASCADE,
  topic          TEXT NOT NULL,
  generated_text TEXT NOT NULL,
  language       TEXT NOT NULL,
  tone           TEXT NOT NULL,
  platform       TEXT NOT NULL,
  hashtags       TEXT[] DEFAULT '{}',
  embedding      VECTOR(384),          -- sentence-transformers (Phase 2)
  was_used       BOOLEAN DEFAULT FALSE,
  was_liked      BOOLEAN DEFAULT FALSE,
  was_edited     BOOLEAN DEFAULT FALSE,
  original_text  TEXT,
  final_text     TEXT,
  created_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_captions_user_id    ON captions (user_id);
CREATE INDEX IF NOT EXISTS idx_captions_was_liked  ON captions (user_id, was_liked);
CREATE INDEX IF NOT EXISTS idx_captions_created_at ON captions (created_at DESC);

-- ============================================================
-- user_events
-- Behavioural log for ML training
-- ============================================================
CREATE TABLE IF NOT EXISTS user_events (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID REFERENCES auth.users ON DELETE CASCADE,
  event_type  TEXT NOT NULL,  -- liked | copied | edited | regenerated | disliked | published
  caption_id  UUID REFERENCES captions ON DELETE CASCADE,
  metadata    JSONB,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_events_user_id    ON user_events (user_id);
CREATE INDEX IF NOT EXISTS idx_user_events_caption_id ON user_events (caption_id);

-- ============================================================
-- scheduled_posts
-- Queue for Phase 2 publishing
-- ============================================================
CREATE TABLE IF NOT EXISTS scheduled_posts (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID REFERENCES auth.users ON DELETE CASCADE,
  caption_id       UUID REFERENCES captions ON DELETE CASCADE,
  platform         TEXT NOT NULL,
  scheduled_at     TIMESTAMPTZ NOT NULL,
  status           TEXT DEFAULT 'pending',   -- pending | published | failed
  platform_post_id TEXT,
  created_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_scheduled_posts_user_id      ON scheduled_posts (user_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_posts_scheduled_at ON scheduled_posts (scheduled_at ASC);

-- ============================================================
-- user_ml_models
-- Serialised sklearn model params per user
-- ============================================================
CREATE TABLE IF NOT EXISTS user_ml_models (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID REFERENCES auth.users ON DELETE CASCADE UNIQUE,
  model_data        JSONB,
  feature_importance JSONB,
  accuracy          FLOAT,
  training_samples  INT,
  last_trained_at   TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- Row Level Security
-- ============================================================
ALTER TABLE user_profiles  ENABLE ROW LEVEL SECURITY;
ALTER TABLE captions        ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_events     ENABLE ROW LEVEL SECURITY;
ALTER TABLE scheduled_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_ml_models  ENABLE ROW LEVEL SECURITY;

-- Policies: users can only see/edit their own rows
CREATE POLICY "own profile"    ON user_profiles  FOR ALL USING (auth.uid() = id);
CREATE POLICY "own captions"   ON captions        FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "own events"     ON user_events     FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "own scheduled"  ON scheduled_posts FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "own ml models"  ON user_ml_models  FOR ALL USING (auth.uid() = user_id);
